name: Monorepo CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'apps/**'
      - 'pnpm-lock.yaml' 
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'apps/**'
      - 'pnpm-lock.yaml'

permissions:
  contents: read 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
 
  install-and-lint-all:
    name: Install Dependencies & Lint All Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Monorepo Dependencies
        run: pnpm install --no-frozen-lockfile 
        working-directory: .
        env:
          PNPM_HOME: ${{ runner.temp }}/.pnpm-home
          PATH: ${{ runner.temp }}/.pnpm-home:${{ env.PATH }}

      - name: Run Monorepo Lint
    
        run: pnpm lint || true 

      - name: Cache pnpm Store
        id: cache-pnpm-store
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

  frontend-ci:
    name: Frontend Build & Test
    runs-on: ubuntu-latest
    needs: install-and-lint-all 
    defaults:
      run:
        working-directory: ./apps/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Restore pnpm Store Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Frontend Dependencies (from store)
        run: pnpm install --offline 
        working-directory: . 
        env:
          PNPM_HOME: ${{ runner.temp }}/.pnpm-home
          PATH: ${{ runner.temp }}/.pnpm-home:${{ env.PATH }}

      - name: Run Frontend Tests
        run: pnpm test 

      - name: Build Frontend Application
        run: pnpm build
        env:
         
          VITE_API_BASE_URL: 'https://api.digitalshop.render.com' 

  frontend-deploy:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: frontend-ci 
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    defaults:
      run:
        working-directory: ./apps/frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Restore pnpm Store Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Frontend Dependencies (from store)
        run: pnpm install --offline 
        working-directory: . 
        env:
          PNPM_HOME: ${{ runner.temp }}/.pnpm-home
          PATH: ${{ runner.temp }}/.pnpm-home:${{ env.PATH }}

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Vercel Deploy
        run: vercel deploy --prebuilt --prod --token ${{ secrets.VERCEL_TOKEN }}
       

  backend-ci:
    name: Backend Build & Test
    runs-on: ubuntu-latest
    needs: install-and-lint-all 
    defaults:
      run:
        working-directory: ./apps/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Restore pnpm Store Cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Backend Dependencies (from store)
        run: pnpm install --offline 
        working-directory: . 
        env:
          PNPM_HOME: ${{ runner.temp }}/.pnpm-home
          PATH: ${{ runner.temp }}/.pnpm-home:${{ env.PATH }}

      - name: Run Backend Tests
        run: pnpm test 

  backend-deploy:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: backend-ci 
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    defaults:
      run:
        working-directory: ./apps/backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup pnpm for Deploy
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Disparar Deploy do Backend no Render
        run: |
          SERVICE_ID="${{ secrets.RENDER_SERVICE_ID }}"
          API_KEY="${{ secrets.RENDER_API_KEY }}"

          # Verifica se os secrets estão configurados
          if [ -z "$SERVICE_ID" ]; then
            echo "Erro: RENDER_SERVICE_ID não configurado nos GitHub Secrets. Impossível disparar deploy."
            exit 1
          fi

          if [ -z "$API_KEY" ]; then
            echo "Erro: RENDER_API_KEY não configurado nos GitHub Secrets. Impossível disparar deploy."
            exit 1
          fi

          echo "Disparando redeploy para o serviço Render com ID: $SERVICE_ID"
          curl -X POST \
               -H "Authorization: Bearer $API_KEY" \
               "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
               -H "Content-Type: application/json" \
               -d '{}'